spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: library-resource-server
          uri: http://localhost:9191
          predicates:
            #            - Path=/api/v1/**
            - Path=/books/**,/api/v1/**
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/library-realm
            # Individual properties can also be provided this way
        #            token-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/token
        #            authorization-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/auth
        #            userinfo-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/userinfo
        #            user-name-attribute: preferred_username
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak-provider
            scope: openid
            client-id: gateway-client
            client-secret: pJvCZauwEpUl4QFBMvrdn1lKlH1CznHQ
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

# Enable these to debug the Authorization flow
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"