# !! settings for local configs from package 'resources/config'
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: "[classpath:/, classpath:/config, classpath:/config/{application}, classpath:/config/{application}/{profile}]"

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URI:https://github.com/rtszh/library-app-configs/}
          search-paths: {application}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888